chore: add custom properties example
bpmn-io/form-js-examples pull request #3
Opened 2022-02-25 12:28 UTC by smbea

Context: form-js@0.7.0 blog post - https://hackmd.io/@u6UL9h2DRky4z02Kmh4Oqw/customPropertiesBlogPost

2022-03-01 12:13 UTC, nikku requested changes
What is missing:

* README

Good start!

2022-03-01 12:13 UTC, nikku commented on custom-properties/customProperties.js
> +function mockFecth(_, _) {
```suggestion
function mockFetch(_, _) {
```

2022-03-01 12:13 UTC, nikku commented on custom-properties/index.html
> +        "version": "0.1.0"
```suggestion
        "version": "0.7.0"
```

2022-03-01 12:13 UTC, nikku commented on custom-properties/customProperties.js
> +  return properties && properties.externalData
```suggestion
  return properties && properties.externalData;
```

2022-03-01 12:13 UTC, nikku commented on custom-properties/customProperties.js
> +      }))
```suggestion
      }));
```

2022-03-01 12:13 UTC, nikku commented on custom-properties/index.html
> +            "externalData": "lala"
Does `lala` make any sense? If not, make it a boolean?

2022-03-01 13:58 UTC, nikku commented
CC @ingorichtsmeier

2022-03-02 08:17 UTC, smbea commented on custom-properties/index.html
> +            "externalData": "lala"
It doesn't. I just changed it to an example API endpoint

2022-03-02 08:21 UTC, nikku commented on custom-properties/customProperties.js
> +function mockFetch(_, _) {
```suggestion
async function preloadData(url, method) {
```

2022-03-02 08:21 UTC, nikku commented on custom-properties/customProperties.js
> +loadForm.then((form) => {
```suggestion
loadForm.then(async (form) => {
```

2022-03-02 08:21 UTC, nikku commented on custom-properties/customProperties.js
> +  components.forEach(field => {
make a for of loop (so nested `await` works).

2022-03-02 08:22 UTC, nikku commented on custom-properties/customProperties.js
> +      const res = mockFetch(endpoint, "GET");
```suggestion
      const res = await preloadData(endpoint, "GET");
```

2022-03-02 08:23 UTC, nikku reviewed
Suggestion to make the example more robust:

* add argument names to fetch
* make fetch async (this is what fetch is always going to be)

2022-03-02 08:26 UTC, smbea commented on custom-properties/customProperties.js
> +  components.forEach(field => {
`for` loop instead of `forEach`? May I ask why?

2022-03-02 09:02 UTC, MaxTru commented
Looks great!

* I tried it out and realized that nothing happens when clicking on `submit`. While this of course is not the focus of the example, I still think that this click on `submit` is a typical action a user would do. So consider to add a `console.log` with the submitted form data, when clicking submit.
* I would give the example index.html a meaningful title:
![Screenshot_20220302_100208](https://user-images.githubusercontent.com/42800119/156329502-d726b46d-8f13-4666-9f01-29ccdfcec323.png)

2022-03-02 09:20 UTC, smbea commented
@MaxTru I changed the html file name to viewer.html.
I added a `console.log` and also an `alert` just so the user has some visual feedback when submitting if they test the example.

2022-03-02 09:51 UTC, MaxTru commented on custom-properties/viewer.html
> +    <!--
consider to add
```html
  <title>Custom properties form-js example</title>
```

2022-03-02 10:31 UTC, smbea commented on custom-properties/viewer.html
> +    <!--
✅

2022-03-02 10:51 UTC, nikku approved these changes
Looks good to me!

2022-03-02 10:51 UTC, merged